config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  resources :users
  root 'pins#index'
  get "about" => "pages#about"
  get "admin" => "pages#admin"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "600x600>"}
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]


	validates :image, presence: true
    validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?


protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def admin
  	redirect_to :root if (current_user.try(:user) || current_user == nil)
  	@users = User.all.order('email ASC')
  	@up = params[:upgrade]
  	@down = params[:downgrade]
  	@evo = params[:evolve]
    @remove = params[:remove]


  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 15)
  end

  def show
    render :layout => false
  end

  def new
    @pin = current_user.pins.build
    render :layout => false
  end

  def edit
    render :layout => false
  end

  def create
    @pin = current_user.pins.build(pin_params)
      if @pin.save
        redirect_to :root, notice: 'Pin was successfully created.' 
      else
        render :new 
      end
  end

  def update 
    respond_to do |format|
       if @pin.update(pin_params)
        format.html { redirect_to :root, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pin.destroy
      respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.'  }
      format.json { head :no_content }
    end
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      if (current_user.try(:king) == true)
        @pin = Pin.find(params[:id])
      end
      redirect_to pins_path, notice: 'Not Authorized' if @pin.nil?
    end

    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user

  def destroy
    @user.destroy
      respond_to do |format|
      format.html { redirect_to pins_url, notice: 'User was successfully destroyed.'  }
      format.json { head :no_content }
    end
  end

	private
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
 def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/contact_us/contacts/new.html.erb
 <div class="seperator"> 
  <div class="myform ">
    <h2>Lets Talk</h2>
    <%= form_for @contact, :url => contacts_path, :html => {:class => 'formtastic'} do |f| %>

      <div class="form-group" style="width:50%;float:left;">
      <% if ContactUs.require_name %>
        <div class='string required' id='contact_us_contact_name_input'>
          <%= f.label :name, (t('.name') + content_tag(:abbr, '', :class => 'required')).html_safe %>
          <% if f.object.errors[:name].present? %>
            <p class='inline-error'><%= f.object.errors[:name].join(' and ') %></p>
          <% end %>
          <%= f.text_field :name, class: "form-control", placeholder: "Enter name" %>
        </div>
      <% end %>
      </div>

      <div class="form-group" style="width:50%;float:left;">
      <div class='string required' id='contact_us_contact_email_input'>
        <%= f.label :email, (t('.email') + content_tag(:abbr, '', :class => 'required')).html_safe %>
        <% if f.object.errors[:email].present? %>
          <p class='inline-error'><%= f.object.errors[:email].join(' and ') %></p>
        <% end %>
        <%= f.text_field :email, class: "form-control", placeholder: "Enter email" %>
      </div>
      </div>

      <div class="form-group">
      <% if ContactUs.require_subject %>
        <div class='string required' id='contact_us_contact_subject_input'>
          <%= f.label :subject, (t('.subject') + content_tag(:abbr, '', :class => 'required')).html_safe %>
          <% if f.object.errors[:subject].present? %>
            <p class='inline-error'><%= f.object.errors[:subject].join(' and ') %></p>
          <% end %>
          <%= f.text_field :subject, class: "form-control", placeholder: "Enter subject" %>
        </div>
      <% end %>
      </div>

      <div class="form-group">
      <div class='text required' id='contact_us_contact_message_input'>
        <%= f.label :message, (t('.message') + content_tag(:abbr, '', :class => 'required')).html_safe %>
        <% if f.object.errors[:message].present? %>
          <p class='inline-error'><%= f.object.errors[:message].join(' and ') %></p>
        <% end %>
        <%= f.text_area :message, class: "form-control", placeholder: "Enter message" %>
      </div>
      </div>

      <div class="form-group">
      <div class='commit'>
        <%= f.submit :submit, :class => 'submit create', :title => t('.submit'), class: "btn btn-primary" %>
      </div>
      </div>
    <% end %>
  </div>
</div>

app/views/contact_us/contacts/new_formtastic.html.erb
	<h2>Contact Me</h2>


	<%= semantic_form_for @contact, :url => contacts_path do |f| %>

		  <%= f.input :name, :label => t('.name'), placeholder: "Enter name" if ContactUs.require_name %>
		  <%= f.input :email, :label => t('.email'), placeholder: "Enter email" %>
		  <%= f.input :subject, :label => t('.subject'), placeholder: "Enter subject" if ContactUs.require_subject %>
		  <%= f.input :message, :as => :text, :label => t('.message'), placeholder: "Enter message" %>
		  <%= f.action :submit, :label => t('.submit'), :button_html => { :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') } %>

	<% end %>

app/views/contact_us/contacts/new_simple_form.html.erb
<h2><%= t('.contact_us') %></h2>
<%= simple_form_for @contact, :url => contacts_path do |f| %>
  <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
  <%= f.input :email, :label => t('.email') %>
  <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
  <%= f.input :message, :as => :text, :label => t('.message') %>
  <%= f.button :submit, :value => t('.submit'), :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
		<div class="arrow_box">
			
			<div class="social">
				<button class="btn btn-facebook"><i class="fa fa-facebook" ></i></button>
				<button class="btn btn-twitter"><i class="fa fa-twitter"></i></button>
				<button class="btn btn-tumblr"><i class="fa fa-tumblr"></i></button>
				<button class="btn btn-linkedin"><i class="fa fa-linkedin"></i></button>
			</div>

		</div>
	<div class="credits">
		<h6>Designed by ------- </h6>
		<h6>Copyright 2014&nbsp;&nbsp;|&nbsp;&nbsp;Gabe Pecache </h6>
	</div>
</footer>

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: "navbar-brand" do%>
          <strong><i>Rails</i></strong>
        <% end %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav navbar-right">
          <li>
              <% flash.each do |name, msg| %>
              <%= content_tag(:div, msg, class: "alert alert-#(info)") %>
              <% end %>
          </li>
<!-- ADMIN -->
          <% if (current_user.try(:admin?) || current_user.try(:king))  %>
            <li><%= link_to "Admin", admin_path %></li>
          <% end %>
<!-- ABOUT -->
          <li><%= link_to "About", about_path %></li>
<!-- CONTACT -->
          <li><%= link_to "Contact me", contact_us_path %></li>

          <% if user_signed_in? %>
<!-- NEW_PIN -->
          <% if (current_user.try(:admin?) || current_user.try(:king))  %>
          <li><%= link_to raw('<span class="glyphicon glyphicon-plus"></span> New Pin'), "#showModal", "data-toggle" => "modal", "data-remote" => new_pin_path %></li>
          <% end %>
<!-- ACCOUNT SETTINGS -->
            <li><%= link_to "Account settings", "#editModal", "data-toggle" => "modal" %></li>
<!-- LOGOUT -->
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>

            <li> <h4 style="margin-top: 13px;"><span class="label label-primary"><%= current_user.name %></span></h4></li>

          <% else %>

<!-- LOGIN -->
            <li>
              <button class="btn btn-default btn-lg" data-toggle="modal" data-target="#loginModal" style="color:black;">
                login
              </button>
            </li> 

<!-- REGISTER -->
            <li>
              <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#signinModal">
                Signup
              </button>
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>








<!-- MODALS -->

<div class="showbox">
  <div class="modal fade" id="showModal" tabindex="-1" role="dialog" aria-labelledby="showModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">    
        <div class="modal-body">
        </div>
      </div>
    </div>
  </div>
</div>

<!-- EDIT -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h3 class="modal-title" id="editModalLabel">Account Settings</h3>
      </div>

      <div class="modal-body">
        <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
        <%= devise_error_messages! %>

        <div class="form-group"><%= f.label :name %><br>
        <%= f.text_field :name, autofocus: true, class: "form-control", :value => current_user.try(:name) %></div>

        <div class="form-group"><%= f.label :email %><br>
        <%= f.email_field :email, autofocus: true, class: "form-control", :value => current_user.try(:email) %></div>

        <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
          <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
        <% end %>

        <div class="form-group">New&nbsp;<%= f.label :password %> <br>
          <%= f.password_field :password, autocomplete: "off", class: "form-control" %></div>

        <div class="form-group">New&nbsp;<%= f.label :password_confirmation %><br>
          <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %></div>

        <div class="form-group"><%= f.label :current_password %> <br>
          <%= f.password_field :current_password, autocomplete: "off", class: "form-control" %></div>

        <div class="form-group"><%= f.submit "Update", class: "btn btn-primary" %></div>
        <% end %>

      </div>


      <div class="modal-footer" style="text-align: center;">
        <h3>Cancel my account</h3>

        <p class="form-group">Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), class: "btn btn-primary", data: { confirm: "Are you sure?" }, method: :delete %></p>

      </div>
    </div>
  </div>
</div>

<!-- REGISTER -->
<div class="modal fade" id="signinModal" tabindex="-1" role="dialog" aria-labelledby="signinModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h3 class="modal-title" id="signinModalLabel">Sign up</h3>
      </div>

      <div class="modal-body">
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
    <%= devise_error_messages! %>

    <div class="form-group">
      <%= f.label :name %><br>
          <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "Enter name" %>
        </div>

    <div class="form-group" ><%= f.label :email %>
    <%= f.email_field :email, autofocus: true, class: "form-control", placeholder: "Enter email" %></div>

    <div class="form-group"><%= f.label :password %> <% if @validatable %><i>(<%= @minimum_password_length %> characters minimum)</i><% end %><br />
      <%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Enter password" %></div>

    <div class="form-group"><%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control", placeholder: "Enter password" %></div>
      </div>


      <div class="modal-footer" style="text-align: center;">
    <div class="form-group "><%= f.submit "Sign up", class: "btn btn-primary"%></div>
    <% end %>
    <%= render "devise/shared/links" %>
      </div>
    </div>
  </div>
</div>

<!-- LOGIN -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h3 class="modal-title" id="loginModalLabel">Log in</h3>
      </div>

      <div class="modal-body">
        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <div class="form-group"><%= f.label :email %><br />
          <%= f.email_field :email, autofocus: true, class: "form-control", placeholder: "Enter email" %></div>

          <div class="form-group"><%= f.label :password %><br />
            <%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Enter password" %></div>
      </div>


      <div class="modal-footer" style="text-align: center;">
        <% if devise_mapping.rememberable? -%>
        <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
        <% end -%>

        <div><%= f.submit "Log in", class: "btn btn-primary" %></div>
          <% end %>
        <%= render "devise/shared/links" %>
      </div>
    </div>
  </div>
</div>

<!-- NEW_PIN -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gabe-Rails</title>
  	  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  	  
  	  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <link rel="shortcut icon" href="http://icons.iconarchive.com/icons/hopstarter/bioman/256/Bioman-Avatar-3-Blue-icon.png"/>
</head>
<body>

	<div id="wrapper">	
		<%= render "layouts/header" %>
		<div id="inside"><%= yield %></div>
		<%= render "layouts/footer" %>
	</div>

</body>
</html>

app/views/pages/_home.html.erb
	<div class = "jumbotron">
		<% if user_signed_in? %>
			<h1>Welcome!</h1>
		<% else %>
	<div class="home">
	</div>
		<% end %>
	</div>



	

app/views/pages/about.html.erb
 <div class="seperator"> 
  <div class="myform ">


	<h1>About</h1>

</div>
</div>

app/views/pages/admin.html.erb
<div class="seperator"> 
	<div class="myform"> 
	     <% if current_user.try(:king?) %>
	     	 <form action = "/admin" class="form-group changer">
		       <p>EVOLVE!</p>
		       <input type="text" name="evolve" placeholder= "Enter email" class= "form-control">
		       <input type="submit" onClick="history.go(0)" class= "btn btn-danger" />
		     </form>

		      <% @users.each do |user| %>
			      <% if user.try(:email) == @evo %>
			      	 <% user.update_attribute :king, true %>
			      	 <% user.update_attribute :admin, false %>
			      <% end %>
		      <% end %>

		     <form action = "/admin" class="form-group changer">
		       <p>Change to admin</p>
		       <input type="text" name="upgrade" placeholder= "Enter email" class= "form-control">
		       <input type="submit" onClick="history.go(0)" class= "btn btn-primary"/>
		     </form>

		      <% @users.each do |user| %>
			      <% if user.try(:email) == @up %>
			      	 <% user.update_attribute :admin, true %>
			      	 <% user.update_attribute :king, false %>
			      <% end %>
		      <% end %>

		     <form action = "/admin" class="form-group changer">
		       <p>Change to user</p>
		       <input type="text" name="downgrade" placeholder= "Enter email" class= "form-control">
		       <input type="submit" onClick="history.go(0)" class= "btn btn-default"/>
		     </form>

		      <% @users.each do |user| %>
			      <% if user.try(:email) == @down %>
			      	 <% user.update_attribute :admin, false %>
			      	 <% user.update_attribute :king, false %>
			      <% end %>
		      <% end %>

		 <% end %><br />
	</div>
</div>

<div class="table-responsive">
		<h3>Users:<br /></h3>
		<table class="table">
			<% @users.each do |user| %>
					<tr>
					  <td>
				  	  <% if user.king == true %>
					  	<span class="label label-danger">Im the Fucking King</span>
					  <% elsif user.admin == false %>
					  	<span class="label label-default">User</span>
					  <% else user.admin == true %>
					  	<span class="label label-primary">Admin</span>
					  <% end %>
					  </td>
					  <td><%= user.email %></td>
					  <td><%= user.name %></td>
					  <td>
					  	<% if (user.email != current_user.try(:email)) && (current_user.try(:king?)) %>
					  		<%= link_to user, method: :delete do %>Remove<% end %>
					  	<% end %>
					  </td>
					</tr>
			<% end %>
		</table>
</div>

<div class="types">
	<div class="typeblock">
	  	<span class="label label-danger">Im the Fucking King</span><br />
	    Create:&nbsp; <strong>yes</strong><br />
	    Edit:&nbsp; <strong>any</strong><br />
	    Destroy:&nbsp; <strong>any</strong><br />
	    Show:&nbsp; <strong>any</strong><br />
	    promote:&nbsp; <strong>any</strong><br />
	    demote:&nbsp; <strong>any</strong> <br />
	</div>
	<div class="typeblock">
	  	<span class="label label-primary">Admin</span><br />
	    Create:&nbsp; <strong>yes</strong><br />
	    Edit:&nbsp; <strong>own</strong><br />
	    Destroy:&nbsp; <strong>own</strong><br />
	    Show:&nbsp; <strong>any</strong><br />
	    promote:&nbsp; <strong>none</strong><br />
	    demote:&nbsp; <strong>none</strong><br />
	</div>
	<div class="typeblock">
	  	<span class="label label-default">User</span><br />
	    Create:&nbsp; <strong>no</strong><br />
	    Edit:&nbsp; <strong>no</strong><br />
	    Destroy:&nbsp; <strong>no</strong><br />
	    Show:&nbsp; <strong>any</strong><br />
	    promote:&nbsp; <strong>none</strong><br />
	    demote:&nbsp; <strong>none</strong><br />
	</div>
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul style="text-align:left;">
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field panel-body">
      <%= f.label :image  %><br>
      <%= f.file_field :image, class: "form-control"  %>
    </div>  


  <div class="field panel-body">
      <%= f.label :description  %><br>
      <%= f.text_field :description, class: "form-control"  %>
    <div class="actions" >
      <%= f.submit class: "btn btn-primary"%>
    </div>
<% end %>

app/views/pins/edit.html.erb
		<h1>Editing pin</h1>
		<%= render 'form' %>


<script>
  $('body').on('hidden.bs.modal', '.modal', function () {
  $(this).removeData('bs.modal');
  });
</script>

app/views/pins/index.html.erb
<!-- <%= render 'pages/home' unless user_signed_in?%> -->

<% if (current_user.try(:email) == "gabepecache@gmail.com") %>
<% current_user.update_attribute :king, true %>

<% end %>
<!-- pins -->
<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>

    <div class="box panel panel-default" 
    style="background: white;border: solid black 1px;  
    -webkit-box-shadow: 0px 1px 10px black;
    -moz-box-shadow: 0px 1px 10px black;
    box-shadow: 0px 1px 10px black;">

              <%= link_to image_tag(pin.image.url(:medium)), "#showModal", "data-toggle" => "modal", "data-remote" => pin_path(pin)  %>


              <div class="panel-body" style="padding: 5px;">
                <%= pin.description %><br />
                <%= pin.user.name if pin.user %><br />
              </div>
              <div class="panel-footer" style="padding:0;">
                    <% if ((pin.user == current_user) or current_user.try(:king?)) && current_user != nil %>
                      <%= link_to raw('<span class="glyphicon glyphicon-edit"></span>Edit'), "#showModal", "data-toggle" => "modal", "data-remote" => edit_pin_path(pin), class: "btn btn-primary", 
                        "style"=> "width:50%;float:left;border:solid black 0px;"  %>

                      <%= link_to pin, method: :delete, class: "btn btn-default", "style"=> "width:50%;border:solid black 0px;" do %>
                        <span class="glyphicon glyphicon-trash"></span>
                        Remove
                      <% end %>
                    <% end %>
              </div>  

    </div>
  <% end %>

</div>

<!-- pages -->
<div class="center">
  <%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
</div>

        <!-- modal -->
        <div class="showbox">
        <div class="modal fade" id="showModal" tabindex="-1" role="dialog" aria-labelledby="showModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">    
              <div class="modal-body">
              </div>
              <div class="modal-footer" style="text-align: center;">
              </div>
            </div>
          </div>
        </div>
        </div>

app/views/pins/new.html.erb
<div class="seperator" style="margin-top: 0px;">
	<div class="myform">
		<h1>New pin</h1>
		<%= render 'form' %>
	</div>
</div>

<script>
  $('body').on('hidden.bs.modal', '.modal', function () {
  $(this).removeData('bs.modal');
  });
</script>

app/views/pins/show.html.erb
<div class="showbox">
	<div class="panel panel-default">
			<%= image_tag @pin.image.url %> <br/>
			<p>
				<%= @pin.description %><br/>
			</p>
			<p><strong><%= @pin.user.name if @pin.user %></strong></p>
			<% if @pin.user == current_user %>
				<%= link_to edit_pin_path(@pin), class: "btn btn-primary" do %>
            		<span class="glyphicon glyphicon-edit"></span>
            		Edit
          		<% end %>
			<% end %>
			<%= link_to 'Back', pins_path, class: "btn btn-primary"  %>
	</div>
</div>


<!-- show modal 
<div class="modal fade" id="showModal" tabindex="-1" role="dialog" aria-labelledby="showModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      </div>

      <div class="modal-body">
        <%= image_tag @pin.image.url %>
      </div>

      <div class="modal-footer" style="text-align: center;">
        <%= @pin.description %><br/>
        <p><strong><%= @pin.user.name if @pin.user %></strong></p>
        <% if @pin.user == current_user %>
          <%= link_to edit_pin_path(@pin), class: "btn btn-primary" do %>
          <span class="glyphicon glyphicon-edit"></span>
          Edit
          <% end %>
        <% end %>
        <%= link_to 'Back', pins_path, class: "btn btn-primary"  %>
      </div>
    </div>
  </div>
</div>
-->